# .github/workflows/destroy_ec2_resources.yml
name: Destroy EC2 Resources
 
on:
  workflow_dispatch:
 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACESS_KEY }}
  AWS_REGION: us-east-1
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_LOGIN_TOKEN }}
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Plan for Destroy
        run: terraform plan -destroy
 
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
 
